<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>T-Mod-Control</AssemblyName>
    <RootNamespace>TMod.Control</RootNamespace>
    <Version>1.2.0</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
    <InvariantGlobalization>false</InvariantGlobalization>
    <SatelliteResourceLanguages>ru</SatelliteResourceLanguages>
    <ApplicationIcon>../../desktop/resources/icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Generated/TModControlPayload.ps1" />
  </ItemGroup>
</Project>
