allowBuilds:
  "@lng2004/node-datachannel": true
  node-av: true
  puppeteer: true
  sharp: true
  zeromq: true

overrides:
  sharp: 0.35.3
  "werift-ice>ip": "npm:neoip@2.1.0"
  "werift>ip": "npm:neoip@2.1.0"
