"use strict";
const $=(id)=>document.getElementById(id), state={data:null,screen:"desk",restore:null};
const el=(tag,cls="",text="")=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!=="")n.textContent=String(text);return n};
const clear=(n)=>{while(n.firstChild)n.firstChild.remove()};
const rid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const statuses={reserved:"Зарезервировано",created:"Открыто",awaiting_close:"Ожидает закрытия",closed:"Закрыто",archived:"В архиве",error:"Нужна проверка"};
const when=(v)=>v?new Date(v).toLocaleString("ru-RU",{dateStyle:"medium",timeStyle:"short"}):"—";
function toast(text,error=false){const n=$("toast");n.textContent=text;n.className=`toast${error?" error":""}`;n.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.hidden=true,4800)}
async function api(url,options={}){const headers={...(options.headers||{})};if(options.body){headers["Content-Type"]="application/json";headers["X-CSRF-Token"]=state.data?.viewer?.csrf_token||"";headers["X-Idempotency-Key"]=rid()}const c=new AbortController(),t=setTimeout(()=>c.abort(),options.timeout||20000);try{const r=await fetch(url,{...options,headers,signal:c.signal,credentials:"same-origin",cache:"no-store"});if(r.status===401){location.assign("/login?next=%2Fsgl");throw new Error("Требуется вход")}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.message||`SGL: HTTP ${r.status}`);return p}finally{clearTimeout(t)}}
function openDialog(n){if(n.showModal)n.showModal();else n.setAttribute("open","")}
function closeDialog(n){if(n.close)n.close();else n.removeAttribute("open")}
function switchScreen(name){state.screen=["desk","cases","archive"].includes(name)?name:"desk";document.querySelectorAll(".screen").forEach(n=>n.classList.toggle("active",n.id===`screen-${state.screen}`));document.querySelectorAll("[data-screen]").forEach(n=>n.classList.toggle("active",n.dataset.screen===state.screen));const meta={desk:["SGL · COMMAND DESK","Оперативный стол"],cases:["SGL · CASE REGISTRY","Реестр дел"],archive:["SGL · DURABLE ARCHIVE","Архив дел"]}[state.screen];$("section-kicker").textContent=meta[0];$("section-title").textContent=meta[1];history.replaceState(null,"",`#/${state.screen}`)}
function miniCase(item){const n=el("article","mini-case");n.append(el("strong","",`№${String(item.case_number).padStart(3,"0")}`));const copy=el("span");copy.append(el("b","",item.client_display||item.client_nick||"Клиент не указан"),el("small","",`${item.request_type||"Обращение"} · ${item.lead_lawyer_display||"команда формируется"}`));n.append(copy,el("small","state",statuses[item.status]||item.status));n.addEventListener("click",()=>showCase(item.case_number));return n}
function caseCard(item){const n=el("article","case-card");n.tabIndex=0;n.append(el("strong","case-number",`№${String(item.case_number).padStart(3,"0")}`));[[item.client_display||item.client_nick||"—",item.request_type||"Клиент"],[item.lead_lawyer_display||"Не назначен","Ведущий юрист"],[statuses[item.status]||item.status,`${item.event_count||0} событий · ${item.receipt_count||0} чеков`]].forEach(([a,b])=>{const s=el("span");s.append(el("b","",a),el("small","",b));n.append(s)});const button=el("button","","Открыть →");button.type="button";n.append(button);n.addEventListener("click",()=>showCase(item.case_number));return n}
function archiveCard(item){const n=el("article","archive-card");n.append(el("strong","case-number",`№${String(item.case_number).padStart(3,"0")}`));const a=el("span");a.append(el("b","",item.original_channel_name||"Архив дела"),el("small","",`${item.message_count||0} сообщений · ${item.attachment_count||0} вложений`));const b=el("span");b.append(el("b","",item.status||"готов"),el("small","",when(item.snapshot_completed_at||item.updated_at)));const button=el("button","","Восстановить");button.type="button";button.disabled=!state.data.viewer.administrator;button.title=button.disabled?"Требуются права администратора":"Создать временный канал в Discord";button.addEventListener("click",e=>{e.stopPropagation();confirmRestore(item)});n.append(a,b,button);return n}
function render(data){state.data=data;$("viewer-name").textContent=data.viewer?.name||"Участник";Object.entries(data.counts||{}).forEach(([k,v])=>{const n=$(`count-${k}`);if(n)n.textContent=String(v||0)});const recent=$("recent-cases");clear(recent);(data.cases?.items||[]).slice(0,5).forEach(i=>recent.append(miniCase(i)));if(!recent.children.length)recent.append(el("div","empty","В реестре пока нет дел."));renderCases();renderArchives();const select=$("case-filter").elements.status,chosen=select.value;clear(select);select.append(new Option("Все состояния",""));(data.cases?.statuses||[]).forEach(s=>select.append(new Option(statuses[s]||s,s)));select.value=chosen}
function renderPublic(data){state.data=data;document.body.classList.add("public-mode");const discordUrl="https://discord.gg/buPmaEgZ9B",secretaryUrl="https://discord.com/users/1010474387352322048";["public-discord-top","public-discord","public-discord-bottom"].forEach(id=>{const n=$(id);if(n)n.href=discordUrl});["public-secretary","public-secretary-bottom"].forEach(id=>{const n=$(id);if(n)n.href=secretaryUrl});$("app").hidden=true;$("public-site").hidden=false;requestAnimationFrame(()=>document.body.classList.add("public-ready"))}
function renderCases(){const n=$("case-list");clear(n);(state.data?.cases?.items||[]).forEach(i=>n.append(caseCard(i)));if(!n.children.length)n.append(el("div","empty","По заданным условиям дел не найдено."))}
function renderArchives(){const n=$("archive-list");clear(n);(state.data?.archives?.items||[]).forEach(i=>n.append(archiveCard(i)));if(!n.children.length)n.append(el("div","empty","Архив пока пуст."))}
async function load(query="",status=""){const p=new URLSearchParams();if(query)p.set("q",query);if(status)p.set("status",status);if(new URLSearchParams(location.search).get("public")==="1")p.set("public","1");const data=await api(`/api/sgl/bootstrap?${p}`);if(data.mode==="public")renderPublic(data);else render(data)}
async function showCase(number){try{const data=await api(`/api/sgl/cases/${encodeURIComponent(number)}`),c=data.case,n=$("case-detail");clear(n);const head=el("header","dossier-head");head.append(el("small","","SGL · ЦИФРОВОЕ ДОСЬЕ"),el("h2","",`Дело №${String(c.case_number).padStart(3,"0")}`),el("span","state",statuses[c.status]||c.status));const body=el("div","dossier-body"),facts=el("div","facts");[["Клиент",c.client_display||c.client_nick],["Статик",c.static_id],["Ведущий юрист",c.lead_lawyer_display],["Секретарь",c.secretary_display],["Тип обращения",c.request_type],["Обновлено",when(c.updated_at)]].forEach(([a,b])=>{const s=el("span");s.append(el("small","",a),el("b","",b||"—"));facts.append(s)});body.append(facts);if(c.situation_text)body.append(el("div","situation",c.situation_text));if(c.discord_url){const a=el("a","reactor-link","Открыть канал в Discord ↗");a.href=c.discord_url;a.target="_blank";a.rel="noreferrer";body.append(a)}const timeline=el("section","timeline");timeline.append(el("h3","","Хронология дела"));(data.events||[]).forEach(e=>{const row=el("article"),copy=el("span");copy.append(el("b","",e.action||"Событие"),el("small","",`${e.actor_display||"T-Mod"}${e.details?` · ${e.details}`:""}`));row.append(el("i"),copy,el("time","",when(e.created_at)));timeline.append(row)});if(!(data.events||[]).length)timeline.append(el("div","empty","Событий пока нет."));body.append(timeline);n.append(head,body);openDialog($("case-dialog"))}catch(e){toast(e.message,true)}}
function confirmRestore(item){state.restore=item;$("confirm-copy").textContent=`Для дела №${String(item.case_number).padStart(3,"0")} будет создан временный защищённый канал с сохранённой перепиской.`;openDialog($("confirm-dialog"))}
async function restore(){if(!state.restore)return;const button=$("confirm-action");button.disabled=true;try{const r=await api("/api/admin/sgl/command",{method:"POST",body:JSON.stringify({action:"restore_archive",case_number:state.restore.case_number,confirmed:true}),timeout:45000});closeDialog($("confirm-dialog"));toast(r.message||"Архив восстановлен");if(r.discord_url)window.open(r.discord_url,"_blank","noopener")}catch(e){toast(e.message,true)}finally{button.disabled=false;state.restore=null}}
function bind(){document.querySelectorAll("[data-screen]").forEach(n=>n.addEventListener("click",()=>switchScreen(n.dataset.screen)));document.querySelectorAll("[data-jump]").forEach(n=>n.addEventListener("click",()=>switchScreen(n.dataset.jump)));document.querySelectorAll("[data-close]").forEach(n=>n.addEventListener("click",()=>closeDialog(n.closest("dialog"))));$("refresh").addEventListener("click",async()=>{try{await load();toast("Реестр обновлён")}catch(e){toast(e.message,true)}});$("case-filter").addEventListener("submit",async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));try{await load(v.q,v.status)}catch(x){toast(x.message,true)}});$("confirm-action").addEventListener("click",restore)}
async function start(){bind();try{await load();$("loading").hidden=true;if(state.data?.mode!=="public"){$("app").hidden=false;switchScreen(location.hash.replace(/^#\//,"")||"desk")}}catch(e){if(!String(e.message).includes("Требуется вход")){$("loading").querySelector("b").textContent="SGL временно недоступен";$("loading").querySelector("small").textContent=e.message}}}start();
