const fmt=n=>new Intl.NumberFormat('ru-RU').format(Number(n||0));
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function json(url){const response=await fetch(url,{credentials:'include',headers:{Accept:'application/json'}});let data={};try{data=await response.json()}catch{}if(!response.ok)throw Object.assign(new Error(data.error||`HTTP ${response.status}`),{status:response.status});return data}
function date(value){if(!value)return 'без ограничения';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'—':parsed.toLocaleString('ru-RU',{day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function renderSummary(s){document.querySelector('#viewer-name').textContent=s.viewer.name;document.querySelector('#balance').textContent=fmt(s.balance_tokens);document.querySelector('#monthly-balance').textContent=`${fmt(s.monthly_balance_tokens)} AT`;document.querySelector('#payg-balance').textContent=`${fmt(s.payg_balance_tokens)} AT`;document.querySelector('#current-plan').textContent=s.plan.name;document.querySelector('#plan-lane').textContent=`Класс моделей: ${s.plan.model_lane}`;document.querySelector('#spent').textContent=`${fmt(s.period_usage.atlas_tokens)} AT`;document.querySelector('#requests').textContent=`${fmt(s.period_usage.requests)} ИИ-запросов`;document.querySelector('#account-period').textContent=s.account.period_ends_at?`Текущий период до ${date(s.account.period_ends_at)}`:'Бессрочный базовый доступ';document.querySelector('#usage-list').innerHTML=s.usage_by_model.length?s.usage_by_model.map(x=>`<article><div><b>${esc(x.model||'Локальный Atlas')}</b><small>${esc(x.model_provider||'внутренний контур')}</small></div><span>${fmt(x.requests)} запросов</span><span>${fmt(x.total_tokens)} токенов модели</span><strong>${fmt(x.atlas_tokens)} AT</strong></article>`).join(''):'<p class="empty-copy">За этот период платных вычислений ещё не было.</p>';const kinds={monthly_allowance:'Месячный резерв',legacy_reserve:'Переходный резерв',ai_usage:'ИИ-вычисление',payment:'Оплата',refund:'Возврат',adjustment:'Корректировка'};document.querySelector('#ledger-list').innerHTML=s.ledger.length?s.ledger.slice(0,12).map(x=>`<article><div><b>${esc(kinds[x.entry_kind]||x.entry_kind)}</b><small>${date(x.created_at)} · ${esc(x.description||'операция')}</small></div><strong class="${Number(x.amount_tokens)<0?'minus':'plus'}">${Number(x.amount_tokens)>0?'+':''}${fmt(x.amount_tokens)} AT</strong></article>`).join(''):'<p class="empty-copy">Операций пока нет.</p>';const statuses={pending:'Ожидает оплаты',paid:'Оплачен',failed:'Ошибка',cancelled:'Отменён',refunded:'Возвращён'};document.querySelector('#orders-list').innerHTML=s.orders.length?s.orders.slice(0,12).map(x=>`<article><div><b>Заказ №${x.id}</b><small>${esc(statuses[x.status]||x.status)} · ${date(x.created_at)}</small></div><strong>${money(Number(x.amount_kopecks)/100)}</strong></article>`).join(''):'<p class="empty-copy">Заказов пока нет.</p>'}
function renderAdmin(m){const panel=document.querySelector('#billing-economics');panel.classList.remove('hidden');document.querySelector('#admin-provider-cost').textContent=`$${Number(m.provider_cost_usd||0).toFixed(4)}`;document.querySelector('#admin-revenue').textContent=money(Number(m.revenue_rub||0));document.querySelector('#admin-orders').textContent=`${fmt(m.paid_orders)} оплаченных заказов`;document.querySelector('#admin-requests').textContent=fmt(m.requests);document.querySelector('#admin-users').textContent=`${fmt(m.active_users)} активных пользователей`;document.querySelector('#admin-tokens').textContent=fmt(m.atlas_tokens);document.querySelector('#admin-models').innerHTML=m.models.length?m.models.map(x=>`<article><div><b>${esc(x.model||'Локальный Atlas')}</b><small>${esc(x.model_provider||'')}</small></div><span>${fmt(x.requests)} запросов</span><span>${fmt(x.atlas_tokens)} AT</span><strong>$${(Number(x.provider_cost_microusd||0)/1000000).toFixed(4)}</strong></article>`).join(''):'<p class="empty-copy">Данных за период пока нет.</p>'}
async function init(){try{const summary=await json('/api/atlas/billing/summary');renderSummary(summary);json('/api/atlas/billing/admin/metrics').then(renderAdmin).catch(()=>{})}catch(error){if(error.status===401){location.replace('/login?next=/account');return}document.querySelector('.account-shell').innerHTML='<section class="account-error"><small>ATLAS ACCOUNT</small><h1>Не удалось загрузить кабинет</h1><p>Обновите страницу. Если ошибка повторится, сообщите исполнителю.</p><button onclick="location.reload()">Повторить</button></section>'}}
init();
