const state={catalog:null,summary:null,choice:null};
const fmt=n=>new Intl.NumberFormat('ru-RU').format(Number(n||0));
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n);
async function json(url,options){const response=await fetch(url,{credentials:'include',...options});let data={};try{data=await response.json()}catch{}if(!response.ok)throw Object.assign(new Error(data.message||data.error||`HTTP ${response.status}`),{status:response.status,data});return data}
function productButton(kind,item){const disabled=!state.catalog?.payments?.enabled;const label=disabled?'Оплата откроется после настройки':'Выбрать пакет';return `<button data-buy="${kind}:${esc(item.code)}" ${disabled?'disabled':''}>${label}<span>→</span></button>`}
function renderCatalog(){const c=state.catalog;document.querySelector('#plans-grid').innerHTML=c.plans.map((p,i)=>`<article class="plan ${i===2?'featured':''}"><header><small>${esc(p.model_lane).toUpperCase()}</small>${i===2?'<span>ОПТИМАЛЬНЫЙ</span>':''}</header><h3>${esc(p.name)}</h3><div class="price">${p.monthly_price_rub?money(p.monthly_price_rub):'Бесплатно'}${p.monthly_price_rub?'<i> / 30 дней</i>':''}</div><p>${esc(p.description)}</p><ul><li><b>${fmt(p.monthly_tokens)} AT</b> вычислительного резерва</li><li>Все ручные функции бесплатно</li><li>Класс моделей: ${esc(p.model_lane)}</li><li>Без автоматического продления</li></ul>${p.code==='free'?'<button disabled>Доступен каждому</button>':productButton('subscription',p)}</article>`).join('');document.querySelector('#packs').innerHTML=c.token_packs.map((p,i)=>`<article class="token-pack"><small>ПАКЕТ ${String(i+1).padStart(2,'0')}</small><strong>${fmt(p.atlas_tokens)} <i>AT</i></strong><span>${money(p.price_rub)}</span>${productButton('token_pack',p)}</article>`).join('');document.querySelectorAll('[data-buy]').forEach(button=>button.addEventListener('click',()=>openCheckout(button.dataset.buy)));const banner=document.querySelector('#test-mode-banner');if(c.payments?.enabled&&c.payments?.test_mode)banner?.classList.remove('hidden')}
function findProduct(kind,code){return kind==='subscription'?state.catalog.plans.find(x=>x.code===code):state.catalog.token_packs.find(x=>x.code===code)}
function checkoutKey(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`}
function openCheckout(value){if(!state.summary){location.href='/login?next=/atlas-billing';return}const [kind,code]=value.split(':');const item=findProduct(kind,code);if(!item)return;state.choice={kind,code,item,checkoutKey:checkoutKey()};document.querySelector('#checkout-title').textContent=item.name;document.querySelector('#checkout-copy').textContent=kind==='subscription'?`${money(item.monthly_price_rub)} · ${fmt(item.monthly_tokens)} AT · 30 дней`:`${money(item.price_rub)} · ${fmt(item.atlas_tokens)} бессрочных AT`;document.querySelector('#offer-check').checked=false;document.querySelector('#receipt-email').value='';document.querySelector('#checkout-submit').disabled=true;document.querySelector('#checkout-status').textContent='';document.querySelector('#checkout').showModal()}
function validateCheckout(){const accepted=document.querySelector('#offer-check').checked;const valid=document.querySelector('#receipt-email').validity.valid&&document.querySelector('#receipt-email').value.trim();document.querySelector('#checkout-submit').disabled=!(accepted&&valid)}
async function checkout(){if(!state.choice||!state.summary){location.href='/login?next=/atlas-billing';return}const button=document.querySelector('#checkout-submit');button.disabled=true;button.textContent='Создаём защищённый заказ…';try{const data=await json('/api/atlas/billing/checkout',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':state.summary.viewer.csrf_token},body:JSON.stringify({product_kind:state.choice.kind,product_code:state.choice.code,checkout_key:state.choice.checkoutKey,receipt_email:document.querySelector('#receipt-email').value.trim()})});const form=document.createElement('form');form.method=data.payment.method;form.action=data.payment.url;Object.entries(data.payment.fields).forEach(([name,value])=>{const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;form.append(input)});document.body.append(form);form.submit()}catch(error){document.querySelector('#checkout-status').textContent=error.message;button.textContent='Повторить';validateCheckout()}}
async function init(){try{state.catalog=await json('/api/atlas/billing/catalog');renderCatalog()}catch{document.querySelector('#plans-grid').innerHTML='<p class="catalog-error">Каталог временно недоступен. Обновите страницу.</p>'}try{state.summary=await json('/api/atlas/billing/summary');const link=document.querySelector('.store-account-link');link.querySelector('span').textContent=state.summary.viewer.name;link.href='/account'}catch(error){if(error.status!==401)console.warn(error)}const path=location.pathname;if(path.endsWith('/success')||path.endsWith('/fail')){const result=document.querySelector('#payment-result');result.classList.remove('hidden');result.classList.toggle('failed',path.endsWith('/fail'));result.innerHTML=path.endsWith('/success')?'<b>Платёж принят</b><span>Статус заказа и баланс обновятся после подписанного подтверждения Robokassa.</span>':'<b>Оплата не завершена</b><span>Atlas Token не зачислены. Заказ можно безопасно повторить.</span>'}}
document.querySelector('#offer-check').addEventListener('change',validateCheckout);document.querySelector('#receipt-email').addEventListener('input',validateCheckout);document.querySelector('#checkout-submit').addEventListener('click',checkout);document.querySelector('#checkout .close').addEventListener('click',()=>document.querySelector('#checkout').close());init();
