const state={data:null,csrf:'',orders:[],blocks:[]};
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=value=>new Intl.NumberFormat('ru-RU').format(Number(value||0));
const rubK=value=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB'}).format(Number(value||0)/100);
const usd=value=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'USD',maximumFractionDigits:4}).format(Number(value||0));
const dt=value=>value?new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';
const uuid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
async function api(url,options={}){const response=await fetch(url,{credentials:'include',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(state.csrf?{'X-CSRF-Token':state.csrf}:{}),...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(response.status===401){location.href=`/login?next=${encodeURIComponent('/atlas-finance-admin')}`;throw new Error('Требуется вход')}if(!response.ok)throw Object.assign(new Error(data.message||data.error||`HTTP ${response.status}`),{data,status:response.status});return data}
function toast(message,error=false){const node=$('#toast');node.textContent=message;node.classList.toggle('error',error);node.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('visible'),4200)}
function setView(name){$$('.view').forEach(node=>node.classList.toggle('active',node.id===name));$$('.rail nav button').forEach(node=>node.classList.toggle('active',node.dataset.view===name));const titles={overview:['ФИНАНСОВЫЙ КОНТУР','Пульс Atlas'],orders:['ПЛАТЁЖНЫЙ КОНТУР','Заказы и сверка'],accounts:['ACCESS & ENTITLEMENTS','Аккаунты Atlas'],legal:['LEGAL VERSION CONTROL','Правовой центр'],content:['PUBLICATION CONTROL','Публичные тексты']};$('#view-kicker').textContent=titles[name][0];$('#view-title').textContent=titles[name][1]}
function renderMetrics(d){const cards=[['ВЫРУЧКА',rubK(d.revenue_kopecks),`${fmt(d.paid_orders)} оплаченных заказов`,''],['СЕБЕСТОИМОСТЬ ИИ',rubK(d.provider_cost_kopecks),`${usd(Number(d.provider_cost_microusd)/1e6)} · OpenRouter`,''],['ПРОЧИЕ РАСХОДЫ',rubK(d.manual_cost_kopecks),'занесены вручную',''],['РАСЧЁТНАЯ ПРИБЫЛЬ',rubK(d.profit_kopecks),`маржа ${d.margin_percent}%`,d.profit_kopecks>=0?'profit':'loss'],['АКТИВНОСТЬ',fmt(d.requests),`${fmt(d.active_users)} пользователей`, '']];$('#metrics').innerHTML=cards.map(x=>`<article class="metric ${x[3]}"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></article>`).join('')}
function renderChart(d){const values=d.daily||[];const max=Math.max(1,...values.map(x=>Number(x.revenue_kopecks)));$('#revenue-chart').innerHTML=values.length?values.map(x=>`<div class="bar" style="height:${Math.max(4,Number(x.revenue_kopecks)/max*100)}%"><span>${esc(x.day)} · ${rubK(x.revenue_kopecks)}</span></div>`).join(''):'<div class="account-result empty">За период нет оплаченных заказов</div>';$('#chart-total').textContent=rubK(d.revenue_kopecks)}
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}
function renderModels(d){$('#models').innerHTML=table(['Модель','Запросы','Токены','Стоимость'],(d.models||[]).map(x=>`<tr><td><strong>${esc(x.model||'—')}</strong><small>${esc(x.model_provider||'')}</small></td><td>${fmt(x.requests)}</td><td>${fmt(x.model_tokens)}</td><td>${usd(Number(x.provider_cost_microusd||0)/1e6)}</td></tr>`))}
function renderOrders(items){state.orders=items;$('#orders-table').innerHTML=table(['Заказ','Пользователь','Продукт','Сумма','Статус','Создан',''],items.map(x=>`<tr><td><strong>№${x.id}</strong><small>${esc(x.provider_operation_id||'без операции')}</small></td><td>${x.user_id}</td><td><strong>${esc(x.product_code)}</strong><small>${fmt(x.atlas_tokens)} AT</small></td><td>${rubK(x.amount_kopecks)}</td><td><span class="status ${esc(x.status)}">${esc(x.status)}</span></td><td>${dt(x.created_at)}</td><td>${x.status==='pending'?`<button data-reconcile="${x.id}">Сверить</button>`:''}</td></tr>`));$$('[data-reconcile]').forEach(button=>button.onclick=()=>reconcile(button))}
async function loadOrders(){try{const q=encodeURIComponent($('#order-query').value.trim());const status=encodeURIComponent($('#order-status').value);const data=await api(`/api/admin/atlas-finance/orders?q=${q}&status=${status}`);renderOrders(data.orders)}catch(error){toast(error.message,true)}}
async function reconcile(button){button.disabled=true;try{const data=await api(`/api/admin/atlas-finance/orders/${button.dataset.reconcile}/reconcile`,{method:'POST',body:'{}',headers:{'X-Idempotency-Key':uuid()}});toast(data.settled?'Оплата подтверждена, доступ начислен':'Статус операции сверён');await loadOrders();await load()}catch(error){toast(error.message,true)}finally{button.disabled=false}}
function renderAccount(summary,userId){$('#account-result').classList.remove('empty');$('#account-result').innerHTML=`<div class="account-cards"><div><small>ПЛАН</small><strong>${esc(summary.plan?.name||summary.account?.plan_code)}</strong></div><div><small>БАЛАНС</small><strong>${fmt(summary.balance_tokens)} AT</strong></div><div><small>ЗАПРОСОВ</small><strong>${fmt(summary.period_usage?.requests)}</strong></div></div><p>Discord ID ${esc(userId)} · период до ${dt(summary.account?.period_ends_at)}</p>`}
function renderProvider(data){const node=$('#provider-state');if(data.status!=='ok'){node.innerHTML=`<div class="account-result empty"><strong>${esc(data.status)}</strong><p>${esc(data.message||'Не удалось получить состояние')}</p></div>`;return}node.innerHTML=`<div class="provider-credit"><div><small>ОСТАЛОСЬ</small><strong>${usd(data.remaining_credits_usd)}</strong></div><div><small>ИЗРАСХОДОВАНО</small><strong>${usd(data.total_usage_usd)}</strong></div><p>Всего приобретено ${usd(data.total_credits_usd)}. Ключ и реквизиты никогда не передаются браузеру.</p></div>`}
async function loadProvider(){try{renderProvider(await api('/api/admin/atlas-finance/external'))}catch(error){renderProvider({status:'unavailable',message:error.message})}}
const slotNames={store_notice:'Дисклеймер магазина',legal_center_intro:'Введение правового центра',footer_note:'Подпись в футере',support_email:'Контактный email'};
function renderContent(data){const slots=data.slots||{},limits=data.limits||{};$('#content-slots').innerHTML=Object.keys(slotNames).map(key=>{const item=slots[key]||{};return `<article class="content-card" data-slot="${key}"><header><small>${esc(slotNames[key])}</small><span>${item.status?`${esc(item.status)} · ${dt(item.created_at)}`:'не переопределён'}</span></header><textarea maxlength="${limits[key]||1200}" placeholder="Текущий статический текст останется, пока здесь нет публикации">${esc(item.content_text||'')}</textarea><footer><button data-save="draft">Сохранить черновик</button><button data-save="publish">Опубликовать</button></footer></article>`}).join('');$$('[data-save]').forEach(button=>button.onclick=()=>saveContent(button))}
async function saveContent(button){const card=button.closest('[data-slot]');button.disabled=true;try{await api('/api/admin/atlas-finance/content',{method:'POST',headers:{'X-Idempotency-Key':uuid()},body:JSON.stringify({slot_key:card.dataset.slot,content_text:$('textarea',card).value,publish:button.dataset.save==='publish'})});toast(button.dataset.save==='publish'?'Текст опубликован':'Черновик сохранён');await load()}catch(error){toast(error.message,true)}finally{button.disabled=false}}
function blockLabel(type){return {section:'РАЗДЕЛ',paragraph:'АБЗАЦ',list:'СПИСОК',notice:'ПРИМЕЧАНИЕ'}[type]||type}
function addBlock(type,value={}){state.blocks.push({type,title:value.title||'',text:value.text||'',items:value.items||['']});renderBlocks()}
function syncBlocks(){state.blocks=$$('.legal-block').map(node=>{const type=node.dataset.type;const base={type,title:$('[data-field="title"]',node)?.value||''};if(type==='list')base.items=($('[data-field="items"]',node)?.value||'').split('\n').map(x=>x.trim()).filter(Boolean);else base.text=$('[data-field="text"]',node)?.value||'';return base})}
function renderBlocks(){const root=$('#legal-blocks');root.innerHTML=state.blocks.map((block,index)=>`<article class="legal-block" data-index="${index}" data-type="${esc(block.type)}"><header><span>${blockLabel(block.type)} · ${String(index+1).padStart(2,'0')}</span><button type="button" data-remove="${index}">Удалить</button></header><label>Заголовок<input data-field="title" value="${esc(block.title||'')}" placeholder="${block.type==='section'?'Обязателен для раздела':'Необязательно'}"></label>${block.type==='list'?`<label>Пункты, каждый с новой строки<textarea data-field="items" rows="5">${esc((block.items||[]).join('\n'))}</textarea></label>`:`<label>Текст<textarea data-field="text" rows="${block.type==='section'?2:5}">${esc(block.text||'')}</textarea></label>`}</article>`).join('');$$('[data-remove]',root).forEach(button=>button.onclick=()=>{syncBlocks();state.blocks.splice(Number(button.dataset.remove),1);renderBlocks()})}
function editFromRevision(id){const item=(state.data?.legal||[]).find(value=>Number(value.id)===Number(id));if(!item)return;const form=$('#legal-form');form.elements.document_key.value=item.document_key;form.elements.version_label.value=item.version_label.replace(/\s*\(.*копия.*\)$/i,'');form.elements.title.value=item.title;form.elements.summary.value=item.summary||'';form.elements.effective_from.value=new Date(item.effective_from).toISOString().slice(0,16);state.blocks=structuredClone(item.blocks||[]);renderBlocks();$('#legal-editor-title').textContent=`На основе V${item.version_number}`;form.scrollIntoView({behavior:'smooth',block:'start'})}
function renderLegal(items){const filter=$('#legal-filter').value;const selected=filter?items.filter(x=>x.document_key===filter):items;$('#legal-history').innerHTML=selected.length?selected.map(item=>`<article class="revision"><header><small>${esc(item.document_key).toUpperCase()} · V${item.version_number}</small><span class="${item.status==='published'?'published':''}">${esc(item.status)}</span></header><h3>${esc(item.version_label)}</h3><p>С ${dt(item.effective_from)} · ${item.blocks?.length||0} блоков</p><footer><button data-edit-revision="${item.id}">В редактор</button>${item.status==='draft'?`<button data-publish="${item.id}">Собрать PDF и опубликовать</button>`:`<a href="/api/admin/atlas-finance/legal/${item.id}/pdf" target="_blank">PDF ↗</a>`}</footer></article>`).join(''):'<div class="account-result empty">Редакций пока нет</div>';$$('[data-publish]').forEach(button=>button.onclick=()=>publishLegal(button));$$('[data-edit-revision]').forEach(button=>button.onclick=()=>editFromRevision(button.dataset.editRevision))}
async function publishLegal(button){if(!confirm('Опубликовать эту редакцию? Предыдущая останется в архиве, но перестанет быть действующей.'))return;button.disabled=true;button.textContent='Собираем PDF…';try{await api(`/api/admin/atlas-finance/legal/${button.dataset.publish}/publish`,{method:'POST',body:'{}',headers:{'X-Idempotency-Key':uuid()}});toast('Редакция опубликована: веб и PDF синхронизированы');await load()}catch(error){toast(error.message,true)}finally{button.disabled=false}}
async function load(){const days=$('#days').value;const rate=$('#usd-rate').value.replace(',','.');const data=await api(`/api/admin/atlas-finance/bootstrap?days=${days}&usd_rub_rate=${encodeURIComponent(rate)}`);state.data=data;state.csrf=data.viewer.csrf_token;$('#viewer-name').textContent=data.viewer.name;$('#viewer-mark').textContent=(data.viewer.name||'A').trim()[0].toUpperCase();$('#updated-at').textContent=`обновлено ${new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}`;renderMetrics(data.dashboard);renderChart(data.dashboard);renderModels(data.dashboard);renderOrders(data.dashboard.recent_orders||[]);renderContent(data.content);renderLegal(data.legal||[])}
$$('.rail nav button').forEach(button=>button.onclick=()=>setView(button.dataset.view));
$('#refresh').onclick=()=>load().catch(error=>toast(error.message,true));$('#days').onchange=$('#refresh').onclick;$('#provider-refresh').onclick=loadProvider;
$('#order-search').onclick=loadOrders;$('#order-query').onkeydown=event=>{if(event.key==='Enter')loadOrders()};
$('#cost-form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget;const button=$('button',form);button.disabled=true;try{const values=new FormData(form);const amount=Math.round(Number(String(values.get('amount')).replace(',','.'))*100);await api('/api/admin/atlas-finance/costs',{method:'POST',headers:{'X-Idempotency-Key':uuid()},body:JSON.stringify({category:values.get('category'),title:values.get('title'),amount_kopecks:amount,occurred_at:`${values.get('occurred_at')}T12:00:00+00:00`,note:values.get('note')})});toast('Расход записан');form.reset();$('input[type="date"]',form).value=new Date().toISOString().slice(0,10);await load()}catch(error){$('output',form).textContent=error.message;toast(error.message,true)}finally{button.disabled=false}};
$('#account-search').onsubmit=async event=>{event.preventDefault();const userId=new FormData(event.currentTarget).get('user_id');try{const data=await api(`/api/admin/atlas-finance/account?user_id=${encodeURIComponent(userId)}`);renderAccount(data.summary,userId);$('#grant-form [name="user_id"]').value=userId}catch(error){toast(error.message,true)}};
$('#grant-form [name="kind"]').onchange=event=>{$$('[data-grant]').forEach(node=>node.hidden=node.dataset.grant!==event.target.value)};
$('#grant-form').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget;const button=$('button',form);button.disabled=true;$('output',form).textContent='';const values=Object.fromEntries(new FormData(form));try{await api('/api/admin/atlas-finance/grants',{method:'POST',headers:{'X-Idempotency-Key':uuid()},body:JSON.stringify(values)});toast(values.kind==='subscription'?'Подписка предоставлена':'Atlas Token начислены');const data=await api(`/api/admin/atlas-finance/account?user_id=${encodeURIComponent(values.user_id)}`);renderAccount(data.summary,values.user_id)}catch(error){$('output',form).textContent=error.message;toast(error.message,true)}finally{button.disabled=false}};
$$('[data-add-block]').forEach(button=>button.onclick=()=>{syncBlocks();addBlock(button.dataset.addBlock)});$('#new-legal').onclick=()=>{state.blocks=[];$('#legal-form').reset();$('#legal-form [name="effective_from"]').value=new Date().toISOString().slice(0,16);addBlock('section');setView('legal')};$('#legal-filter').onchange=()=>renderLegal(state.data?.legal||[]);
$('#legal-form').onsubmit=async event=>{event.preventDefault();syncBlocks();const form=event.currentTarget;const button=$('button.primary',form);button.disabled=true;try{const values=Object.fromEntries(new FormData(form));values.effective_from=new Date(values.effective_from).toISOString();values.blocks=state.blocks;const result=await api('/api/admin/atlas-finance/legal',{method:'POST',headers:{'X-Idempotency-Key':uuid()},body:JSON.stringify(values)});toast(`Черновик V${result.version_number} сохранён`);await load()}catch(error){$('output',form).textContent=error.message;toast(error.message,true)}finally{button.disabled=false}};
document.addEventListener('DOMContentLoaded',()=>{$('#cost-form input[type="date"]').value=new Date().toISOString().slice(0,10);$('#legal-form [name="effective_from"]').value=new Date().toISOString().slice(0,16);addBlock('section');load().then(loadProvider).catch(error=>toast(error.message,true))});
